HMS_project/hotel/urls.py
from django.urls import path

from hotel import views

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("rooms/", views.rooms, name="rooms"),
    path("about/", views.about, name="about"),
    path("detail/<slug>/", views.hotel_detail, name="hotel-detail"),
    path("detail/<slug>/", views.hotel_detail, name="hotel-detail"),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('add_hotel_to_cart/<slug:hotel_slug>/', views.add_hotel_to_cart, name='add_hotel_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_quantity/<int:item_id>/', views.update_quantity, name='update_quantity'),
    path('booking/<slug:slug>', views.create_booking, name='create_booking'),

]

HMS_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("userauths.urls")),
]

HMS_project/userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),
    
]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up")
]

HMS_project/hotel/models.py
from django.db import models
from django.utils.text import slugify 
from django.utils.html import mark_safe
from userauths.models import User
from shortuuid.django_fields import ShortUUIDField
import shortuuid
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager

# Create your models here.

HOTEL_STATUS =(
    ('Draft', 'Draft'),
    ('Disable', 'Disable'),
    ('Rejected', 'Rejected'),
    ('In Review', 'In Review'),
    ('Live', 'Live'),
)

ICON_TYPE =(
    ('Bootsrap Icons', 'Bootsrap Icons'),
    ('Fontawesome Icons', 'Fontawesome Icons'),
    ('Box Icons', 'Box Icons'),
    ('Remi Icons', 'Remi Icons'),
    ('Flat Icons', 'Flat Icons'),
)

PAYMENT_STATUS =(
    ('Paid', 'Paid'),
    ('Pending', 'Pending'),
    ('Rejected', 'Rejected'),
    ('Processing', 'Processing'),
    ('cancelled', 'cancelled'),
    ('failed', 'failed'),
    ('refunding', 'refunding'),
    ('refunded', 'refunded'),
    ('unpaid', 'unpaid'),
    ('expired', 'expired'),
    
)


class Hotel(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    description = CKEditor5Field(null=True, blank=True, config_name='extends')
    address = models.CharField(max_length=256)
    image = models.FileField(upload_to = "hotel_gallery")
    mobile = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=HOTEL_STATUS, default = "Live")

    tags = TaggableManager( blank=True)
    views = models.IntegerField(default=0)
    featured = models.BooleanField(default=False)
    hid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvwxyz" )
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now_add=True)
    rating = models.IntegerField(default=0, blank=True, null=True)
      

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniquied = uuid_key[:4]
            self.slug = slugify(self.name) + '-' + str(uniquied.lower())

        super(Hotel, self).save(*args, **kwargs)  

    def thumbnail(self):
        return mark_safe("<img src='%s' width='50' height='50' style='object-fit: cover; border-radius: 6px' />" % self.image.url) 

    def hotel_gallery(self):
        return HotelGallery.objects.filter(hotel=self)   
    
    def get_star_icons(self):
        if self.rating is not None:
            return f'<i class="bi bi-star-fill"></i>' * self.rating
        return ''

    def __str__(self):
        return self.name    


class HotelGallery(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    image = models.FileField(upload_to="hotel_gallery")
    hgid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvwxyz" )

    def __str__(self):
        return str(self.hotel.name)
    
    class Meta:
        verbose_name_plural = "Hotel Gallery"

class HotelFeatures(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    icon_type = models.CharField(max_length=100, null=True , blank=True, choices=ICON_TYPE)   
    icon = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name_plural = "Hotel Features"

class HotelFags(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)   
    answer = models.CharField(max_length=1000, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return str(self.question)
    
    class Meta:
        verbose_name_plural = "Hotel FAQS"


class RoomType(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    type = models.CharField(max_length=10)   
    price = models.DecimalField(max_digits=12, decimal_places=2 , default=0.00)
    number_of_beds = models.PositiveIntegerField(default=0)
    room_capacity = models.PositiveIntegerField(default=0)
    rtid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvwxyz")
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now_add=True) 

    def __str__(self):
        return f"{self.type} - {self.hotel.name} "
    
    class Meta:
        verbose_name_plural = "Room Type"

    def rooms_count(self):
        Room.objects.filters(room_type=self).count()

    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniquied = uuid_key[:4]
            self.slug = slugify(self.name) + '-' + str(uniquied.lower())

        super(RoomType, self).save(*args, **kwargs) 

class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=1000)
    is_available = models.BooleanField(default=True)
    rid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvwxyz")
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.room_type} - {self.hotel.name} - {self.price()}"

    class Meta:
        verbose_name_plural = "Rooms"

    def price(self):
        return self.room_type.price

    def number_of_beds(self):
        return self.room_type.number_of_beds



class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings_user')
    payment_status = models.CharField(max_length=100, null=True, blank=True, choices=PAYMENT_STATUS)

    full_name = models.CharField(max_length=1000)
    email = models.CharField(max_length=1000)
    phone = models.CharField(max_length=1000)

    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='bookings_hotel')
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True, blank=True)
    room = models.ManyToManyField(Room)

    before_discount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    check_in_date = models.DateField()
    check_out_date = models.DateField()

    total_days = models.PositiveIntegerField(default=0)
    num_adults = models.PositiveIntegerField(default=0)
    num_children = models.PositiveIntegerField(default=0)

    is_active = models.BooleanField(default=False)

    check_in_date_tracker = models.BooleanField(default=False)
    check_out_date_tracker = models.BooleanField(default=False)

    booking_id = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvwxyz")
    date = models.DateTimeField(auto_now_add=True)
    success_id = models.CharField(max_length=1000, null=True, blank=True)
    stripe_payment_intent = models.CharField(max_length=1000, null=True, blank=True)
    

    def __str__(self):
        return f"{self.booking_id}"    
    
    def __str__(self):
        return self.room.all().count()  
    def __str__(self):
        return f"{self.full_name} - {str(self.booking_id)}"
 
    
class Activitylog(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    guess_out = models.DateTimeField()    
    guess_in = models.DateTimeField()
    discribtion = models.TextField(null=True, blank = True)
    date = models.DateTimeField(auto_now_add=True)        

    def __str__(self):
        return f"{self.booking}" 

class StaffOnDuty(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    staff_id = models.CharField(max_length=100,null=True, blank = True )
    date = models.DateTimeField(auto_now_add=True)           

    def __str__(self):
        return f"{self.staff_id}" 
    
 
class HotelCartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    imagecart = models.ImageField(upload_to='cart_image', default='default_image.jpg')
    price = models.DecimalField(max_digits=12, decimal_places=2 , default=0.00)


    # Add other fields if needed

    def __str__(self):
        return f"{self.quantity} x {self.room_type} in cart for {self.user.username}" 

hotel/models.py
from django.db import models

# Create your models here.

HMS_project/hotel/forms.py
from django import forms
from .models import Booking

class UpdateQuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)





class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = '__all__'

HMS_project/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

class UserRegisterForm(UserCreationForm):

    full_name = forms.CharField(label='Full Name', widget=forms.TextInput(attrs={'placeholder':"Enter full name",'class':"fullname"}))
    username = forms.CharField(label='Username',widget=forms.TextInput(attrs={'placeholder':"Enter username",'class':"username"}))
    email = forms.CharField(label='Email',widget=forms.TextInput(attrs={'placeholder':"Enter email",'class':"email"}))
    phone = forms.CharField(label='Phone Number',widget=forms.TextInput(attrs={'placeholder':"Enter phone number",'class':"phone"}))
    password1 = forms.CharField(label='Password',widget=forms.TextInput(attrs={'placeholder':"Enter password",'class':"password"}))
    password2 = forms.CharField(label='Confirm Password',widget=forms.TextInput(attrs={'placeholder':"Enter confirm password",'class':"password"}))
    class Meta:
        model = User 
        fields = ['full_name', 'username', 'email','phone', 'password1', 'password2']  

HMS_project/hotel/views.py
from django.shortcuts import render,get_object_or_404,redirect
from hotel.models import Hotel,Booking,Activitylog,StaffOnDuty,Room,RoomType,HotelFags,HotelFeatures,HotelGallery,HotelCartItem
from .forms import UpdateQuantityForm
from .forms import BookingForm






# Create your views here.

def index(request):
    hotels = Hotel.objects.filter(status="Live")
    
    context={'hotels': hotels}
    
    return render(request, "hotel/hotel.html", context)


def rooms(request):
    hotels = Hotel.objects.all()
    context={'hotels': hotels,}
    
    return render(request, "hotel/rooms.html", context)

def about(request):

    return render(request, "hotel/about.html")

def hotel_detail(request,slug):
    hotel = Hotel.objects.get( slug=slug)
    hotels = Hotel.objects.filter(slug=slug)
    room_types = RoomType.objects.filter(hotel=hotel)
    
    context={'hotel': hotel, 'hotels': hotels, 'room_types': room_types }
    return render(request, "hotel/hotel_detail.html", context)

def view_cart(request):
    cart_items = HotelCartItem.objects.filter(user=request.user)
    total_price = sum(item.room_type.price * item.quantity for item in cart_items)
    
   
    return render(request, 'hotel/newcart.html', {'cart_items': cart_items, 'total_price': total_price})

def add_hotel_to_cart(request, hotel_slug):
    hotel = Hotel.objects.get(slug=hotel_slug)
    room_types = RoomType.objects.filter(hotel=hotel)
    
    
    for room_type in room_types:
        user_id = request.user.id
        cart_item, created = HotelCartItem.objects.get_or_create(room_type=room_type, user_id=user_id)
        cart_item.quantity += 1
        cart_item.save()

    return redirect('hotel:view_cart')

def remove_from_cart(request, item_id):
	cart_item = HotelCartItem.objects.get(id=item_id)
	cart_item.delete()
	return redirect('hotel:view_cart')


def update_quantity(request, item_id):
    item = HotelCartItem.objects.get(pk=item_id)

    if request.method == 'POST':
        form = UpdateQuantityForm(request.POST)
        if form.is_valid():
            new_quantity = form.cleaned_data['quantity']
            item.quantity = new_quantity
            item.save()
            # Redirect to the cart page after updating the quantity
            return redirect('hotel:view_cart')
    else:
        form = UpdateQuantityForm(initial={'quantity': item.quantity})

    return render(request, 'hotel/newcart.html', {'form': form, 'item': item})





def create_booking(request, slug):
    hotel = Hotel.objects.get(slug=slug)

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            # Set the hotel field of the form to the current hotel
            form.instance.hotel = hotel

            # Save the form data to the database
            booking_instance = form.save()

            # Redirect to the hotel detail page with the same slug
            return redirect('hotel:hotel-detail', slug=slug)
    else:
        form = BookingForm()

    return render(request, 'hotel/create_booking.html', {'form': form, 'hotel': hotel})

HMS_project/userauths/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth import logout
from userauths.models import User,Profile
from userauths.forms import UserRegisterForm



# Create your views here.

def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, f'You are already logged in.')
    form = UserRegisterForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get('full_name')
        phone = form.cleaned_data.get('phone')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')
        
        user = authenticate(email=email, password=password) 
        login(request,user)

        messages.success(request, f"Account created for {full_name}! You are now logged in.")
        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name 
        profile.phone = phone 
        profile.save()

        return redirect( "hotel:index")

    context = {
        "form": form
    }
    return render(request,"userauths/sign-up.html", context)



def loginViewTemp(request):

    if request.user.is_authenticated:
        messages.warning(request, f'You are already logged in.')
        return redirect("hotel:index")
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user_query = User.objects.get(email=email)
            user_auth = authenticate(request, email=email, password=password) 

            if user_query is not None:
                login(request, user_auth)
                messages.success(request, f"You are logged in")
                next_url = request.GET.get("next", "hotel:index")
                return redirect(next_url)
            else:
                messages.error(request, f'Username or password does not exist')
                return redirect("userauths:sign-in")
            
        except:
            messages.error(request, f'User does not exist')
            return redirect("userauths:sign-in")
                

    return render(request,"userauths/sign-in.html")


def LogoutView(request):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect("hotel:index")

hotel/views.py
from django.shortcuts import render

# Create your views here.

HMS_project/templates/hotel/create_booking.html
<!-- create_booking.html -->



  <h2>Create Booking</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

HMS_project/templates/hotel/hotel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static '/css/hotel.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>Document</title>
</head>

<body>

  <div class="nav-container">
    <div class="items"><a href=""><img src="{% static '/images/free-dolphin-42-450306.png' %}" alt="..logo"
          id="logo"></a></div>
    <div class="items"><a href="#">Home</a></div>
    <div class="items"><a href="{%  url 'hotel:about' %}">About</a></div>
    <div class="items"><a href="{%  url 'hotel:rooms' %}">Rooms</a></div>
    <div class="items"><a href="#">Explore</a></div>
    <div class="items">
      {% if request.user.is_authenticated %}
      <a href="#"><button class="btn btn-outline-warning" id="dash">User DashBoard</button></a>

      {% else %}
      <a href="{% url 'userauths:sign-in'%}"><button id="login">Log In</button></a>
      {% endif %}
      
    </div>
    
    <div class="items">
      {% if request.user.is_authenticated %}
      <a href="#"><img src="{% static '/images/cat.png' %}" alt="logoavatar" id="logoavatar"></a>

      {% else %}
      <a href="{% url 'userauths:sign-up'%}"><button id="btns">Sign Up</button></a>
      {% endif %}
    </div>

  </div>




  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static '/images/Hotel-WordPress-Theme-Slider-5.jpg' %}" class="d-block " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/Hotel-WordPress-Theme-Slider-6.jpg' %}" class="d-block " alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/Hotel-WordPress-Theme-Slider-7.jpg' %}" class="d-block " alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="main-container">
    {% if request.user.is_authenticated %}
    <h1>Welcome back {{ request.user.username}}</h1>
    <a href="{% url 'userauths:sign-out'%}"><button id="btns">Logout</button></a>


    {% else %}
    <h1>Welcome back</h1>
    <div class="main-btn">
      <a href="{% url 'userauths:sign-up'%}"><button id="btns">Sign Up</button></a>
      <a href="{% url 'userauths:sign-in'%}"><button id="btns">Login</button></a>
    </div>

    {% endif %}
  </div>

  <div class="hotel-container">
    {% for hotel in hotels %}
    <div class="card" style="width: 18rem;">
      <img src="{{hotel.image.url}}" class="card-img-top" alt="..." id="hotel-pic">
      <div class="card-body">
        <h5 class="card-title">{{hotel.name}}</h5>
        <p class="card-text">{{ hotel.description|truncatewords:16|safe}}</p>
        <a href="#" class="btn btn-primary">Select Rooms</a>
      </div>
    </div>
    {% endfor %}
  </div>



  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

HMS_project/templates/hotel/hotel_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static '/css/detailpage.css' %}">
    <title>Document</title>
</head>

<body>
    <div class="nav-container">
        <div class="items"><a href=""><img src="{% static '/images/free-dolphin-42-450306.png' %}" alt="..logo"
                    id="logo"></a></div>
        <div class="items"><a href="{% url 'hotel:index'%}">Home</a></div>
        <div class="items"><a href="{%  url 'hotel:about' %}">About</a></div>
        <div class="items"><a href="{%  url 'hotel:rooms' %}">Rooms</a></div>
        <div class="items"><a href="#">Explore</a></div>
        <div class="items">
            {% if request.user.is_authenticated %}
            <a href="#"><button class="btn btn-outline-warning" id="dash">User DashBoard</button></a>

            {% else %}
            <a href="{% url 'userauths:sign-in'%}"><button id="login">Log In</button></a>
            {% endif %}

        </div>
        <div class="items">
            {% if request.user.is_authenticated %}
            <a href="#"><img src="{% static '/images/cat.png' %}" alt="logoavatar" id="logoavatar"></a>

            {% else %}
            <a href="{% url 'userauths:sign-up'%}"><button id="btns">Sign Up</button></a>
            {% endif %}
        </div>
    </div>

    {% for hotel in hotels %}

    <div class="container-fluid-md imagedetail bg-info">
        <img src="{{hotel.image.url}}" class="img-fluid" alt="..." id="detailImage" />
        <div class="container rooms">
            {% for hotel_gallery in hotel.hotel_gallery.all %}
            <div class="item1">
                <img src="{{hotel_gallery.image.url}}" alt="..." class="img-fluid">
            </div>
            {% endfor %}

        </div>
    </div>
    {% endfor %}

    {% for hotel in hotels %}
    <div class="container-md details">
        <div class="base1">
            <h3>{{hotel.name}}</h3>
            <div class="raate"><i class="bi bi-geo-alt-fill"></i>
                <p>{{hotel.address}}</p>
            </div>
            <div class="raate"><i class="bi bi-telephone-fill"></i>
                <p>{{hotel.mobile}}</p>
            </div>
            <div class="raate"><i class="bi bi-envelope"></i>
                <p>{{hotel.email}}</p>
            </div>
            <div class="raate">
                <p>Rating:</p>
                <div class="rating-star">
                    <p>{{ hotel.get_star_icons|safe }}</p>
                </div>
            </div>
        </div>
        <div class="base2">
            {% for room in room_types %}
            <h5>Price: {{ room.price}}</h5>
            <h5>id: {{ room.id}}</h5>
            <form method="post" action="{% url 'hotel:add_hotel_to_cart' hotel_slug=hotel.slug %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Add Hotel to Cart</button>
            </form>
            
            {% endfor %}
            <a href="{% url 'hotel:create_booking' slug=hotel.slug %}" class="btn btn-success">Book Now</a>
            
        </div>
        <div class="base3">
            <h5>Discription</h5>{{ hotel.description|safe}}
        </div>
    </div>
    {% endfor %}

    <div class="container tags">
        {% for t in hotel.tags.all %}
        <a href="#" class="btn btn-info"><i class="bi bi-tag-fill"></i>{{t.name}}</a>
        {% endfor %}

        <div class="Comments"><label>Comments <i class="bi bi-chat-left-dots-fill"></i></label><textarea name="" id=""
                cols="70" rows="5"></textarea></div>
        <button class="btn btn-success">Post</button>

    </div>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    


</body>

</html>

HMS_project/templates/hotel/newcart.html
<h1>Your Shopping Cart</h1>

<div class="product-list">



{% for item in cart_items %}
<div class="product-item">
    <p>hotel Name: {{ item.room_type }} </p>
    <p>quantity:{{ item.quantity }}</p>
    <img src="{{ item.imagecart.url }}" alt="Product Image" style="width: 20%;"/>
    <p>Price: ${{ item.price }}</p>
    <form method="post" action="{% url 'hotel:update_quantity' item.id %}">
        {% csrf_token %}
        {{ update_quantity_form.quantity }}
        <input type="number" name="quantity" value="{{ item.quantity }}" min="1" required>
        <button type="submit">Update Quantity</button>
        
    </form>
    <a href="{% url 'hotel:remove_from_cart' item.id %}">Remove</a>
</div>
{% empty %}
<p>Your cart is empty.</p>
{% endfor %}

{% for hotel in hotels %}
<img src="{{hotel.image.url}}" class="img-fluid" alt="..." id="detailImage" />

{% endfor %}

<p>Total Price: ${{ total_price }}</p>